<?php declare(strict_types=1); ?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Licenze · Agentic AI Operator System</title><link rel="stylesheet" href="assets/admin.css"></head><body>
<main class="shell <?= $authenticated ? '' : 'auth-shell' ?>">
<?php if (!$authenticated): ?>
<section class="auth-card" aria-labelledby="login-title"><div class="brand"><span class="brand-mark">AI</span><span>Agentic AI Operator System</span></div><h1 id="login-title">Area amministrativa</h1><p>Accedi per gestire licenze, scadenze e dispositivi autorizzati.</p><?php if ($error): ?><p class="notice error" role="alert"><?= htmlspecialchars($error) ?></p><?php endif; ?><form method="post" class="stack"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf']) ?>"><input type="hidden" name="action" value="login"><label class="field">Password amministratore<input class="input" type="password" name="password" autocomplete="current-password" required autofocus></label><button class="button">Accedi</button></form></section>
<?php else: ?>
<header class="topbar"><div class="brand"><span class="brand-mark">AI</span><span>Agentic AI Operator System</span></div><form method="post"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf']) ?>"><button class="button secondary" name="action" value="logout">Esci</button></form></header>
<section class="page-heading"><div><h1>Licenze</h1><p>Controlla accessi, scadenze e dispositivi associati da un unico spazio.</p></div><button class="button" type="button" data-dialog="create-license">Nuova licenza</button></section>
<?php if ($message): ?><p class="notice" role="status"><?= htmlspecialchars($message) ?></p><?php endif; ?><?php if ($error): ?><p class="notice error" role="alert"><?= htmlspecialchars($error) ?></p><?php endif; ?>
<?php if ($keyContext): $installationMessage="Ciao ".$keyContext['customer_name'].",\n\ninstalla Agentic AI Operator System per Windows dalla release ufficiale:\nhttps://github.com/IntelligenzaArtificiale/agentic-ai-operator-system/releases/latest\n\nScarica lo ZIP della release, estrailo ed esegui Install-System.ps1 seguendo INSTALL_FOR_CHATGPT.md. Al termine apri la finestra 'Attiva Agentic AI Operator System' e inserisci questa licenza:\n".$keyContext['license_key']."\n\nCompleta l'attivazione, chiudi completamente ChatGPT/Codex e riaprilo in una nuova attività. Verifica infine che installazione e licenza risultino attive."; ?><section class="delivery" aria-label="Consegna licenza"><div class="delivery-head"><div><span>Chiave di licenza</span><strong><?= htmlspecialchars($keyContext['customer_name']) ?></strong></div><button class="button secondary" type="button" data-copy="visible-key">Copia chiave</button></div><code id="visible-key"><?= htmlspecialchars($keyContext['license_key']) ?></code><div class="delivery-message"><div class="delivery-head"><span>Messaggio pronto da inviare</span><button class="button secondary" type="button" data-copy="installation-message">Copia messaggio</button></div><pre id="installation-message"><?= htmlspecialchars($installationMessage) ?></pre></div></section><?php endif; ?>
<?php $visibleActive=0;$visibleDevices=0;foreach($licenses['items'] as $summaryLicense){$isExpired=strtotime($summaryLicense['expires_at'])<=time();if(!$isExpired&&$summaryLicense['status']==='active'){$visibleActive++;}$visibleDevices+=count(array_filter($summaryLicense['devices'],static fn($device)=>empty($device['revoked_at'])));} ?>
<section class="overview" aria-label="Riepilogo licenze"><div class="metric"><span>Licenze trovate</span><strong><?= (int)$licenses['total'] ?></strong></div><div class="metric"><span>Attive in questa pagina</span><strong><?= $visibleActive ?></strong></div><div class="metric"><span>Dispositivi in questa pagina</span><strong><?= $visibleDevices ?></strong></div></section>
<section class="toolbar" aria-label="Strumenti licenze"><form method="get" class="search" role="search"><input class="input" name="q" value="<?= htmlspecialchars($search) ?>" placeholder="Cerca nome, email, telefono o chiave" aria-label="Cerca licenze"><button class="button secondary">Cerca</button></form></section>
<section class="license-list" aria-label="Elenco licenze"><div class="license-columns" aria-hidden="true"><span>Cliente</span><span>Licenza</span><span>Scadenza</span><span>Dispositivi</span><span></span></div>
<?php foreach($licenses['items'] as $license):$expired=strtotime($license['expires_at'])<=time();$activeDevices=count(array_filter($license['devices'],static fn($device)=>empty($device['revoked_at'])));$statusLabels=['active'=>'Attiva','suspended'=>'Sospesa','revoked'=>'Revocata']; ?>
<details class="license-row"><summary class="license-summary"><span class="identity"><strong><?= htmlspecialchars($license['customer']['name']) ?></strong><span><?= htmlspecialchars($license['customer']['email']) ?></span></span><span class="identity"><span class="status <?= htmlspecialchars($expired?'expired':$license['status']) ?>"><?= htmlspecialchars($expired?'Scaduta':($statusLabels[$license['status']]??$license['status'])) ?></span><span><?= htmlspecialchars($license['key_prefix']) ?>…</span></span><span class="cell-muted"><?= htmlspecialchars((new DateTimeImmutable($license['expires_at']))->setTimezone(new DateTimeZone((string)$config->get('admin_timezone')))->format('d/m/Y H:i')) ?></span><span><?= $activeDevices ?>/<?= (int)$license['device_limit'] ?></span><span class="chevron" aria-hidden="true">+</span></summary>
<div class="license-detail"><form method="post" class="manage"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf']) ?>"><input type="hidden" name="action" value="update"><input type="hidden" name="license_id" value="<?= htmlspecialchars($license['license_id']) ?>"><label class="field">Stato<select class="input" name="status"><?php foreach(['active'=>'Attiva','suspended'=>'Sospesa','revoked'=>'Revocata'] as $status=>$label): ?><option value="<?= $status ?>" <?= $license['status']===$status?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label><label class="field">Scadenza<input class="input" type="datetime-local" name="expires_at" value="<?= htmlspecialchars((new DateTimeImmutable($license['expires_at']))->setTimezone(new DateTimeZone((string)$config->get('admin_timezone')))->format('Y-m-d\TH:i')) ?>" required></label><label class="field">Limite dispositivi<input class="input" type="number" name="device_limit" min="1" max="20" value="<?= (int)$license['device_limit'] ?>"></label><button class="button">Salva modifiche</button></form>
<?php if($license['devices']): ?><div class="devices"><h3>Dispositivi associati</h3><?php foreach($license['devices'] as $device): ?><div class="device"><span><strong><?= htmlspecialchars($device['device_name']) ?></strong><small>Ultimo accesso <?= htmlspecialchars($device['last_seen_at']) ?></small></span><?php if(empty($device['revoked_at'])): ?><form method="post"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf']) ?>"><input type="hidden" name="action" value="revoke_device"><input type="hidden" name="license_id" value="<?= htmlspecialchars($license['license_id']) ?>"><input type="hidden" name="activation_id" value="<?= htmlspecialchars($device['activation_id']) ?>"><button class="button danger">Revoca</button></form><?php else: ?><span class="status revoked">Revocato</span><?php endif; ?></div><?php endforeach; ?></div><?php endif; ?><div class="license-actions"><form method="post"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf']) ?>"><input type="hidden" name="action" value="reveal_key"><input type="hidden" name="license_id" value="<?= htmlspecialchars($license['license_id']) ?>"><button class="button secondary">Visualizza chiave</button></form><form method="post" data-confirm="La vecchia chiave e tutti i dispositivi associati verranno invalidati. Continuare?"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf']) ?>"><input type="hidden" name="action" value="regenerate_key"><input type="hidden" name="license_id" value="<?= htmlspecialchars($license['license_id']) ?>"><button class="button secondary">Rigenera chiave</button></form><button class="button danger" type="button" data-dialog="delete-<?= htmlspecialchars($license['license_id']) ?>">Elimina definitivamente</button></div></div></details><dialog id="delete-<?= htmlspecialchars($license['license_id']) ?>"><form method="post"><div class="dialog-head"><h2>Elimina licenza</h2><button class="button secondary icon-button" type="button" data-close aria-label="Chiudi">×</button></div><div class="dialog-body"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf']) ?>"><input type="hidden" name="action" value="delete_license"><input type="hidden" name="license_id" value="<?= htmlspecialchars($license['license_id']) ?>"><p class="danger-copy">Stai eliminando definitivamente la licenza di <strong><?= htmlspecialchars($license['customer']['name']) ?></strong>, tutti i dispositivi e lo storico associato. L’operazione non può essere annullata.</p><label class="field">Scrivi ELIMINA per confermare<input class="input" name="confirmation" pattern="ELIMINA" autocomplete="off" required></label><div class="dialog-actions"><button class="button secondary" type="button" data-close>Annulla</button><button class="button danger">Elimina definitivamente</button></div></div></form></dialog>
<?php endforeach; ?><?php if(!$licenses['items']): ?><p class="empty">Nessuna licenza corrisponde alla ricerca.</p><?php endif; ?></section>
<?php if($licenses['pages']>1): ?><nav class="pages" aria-label="Pagine licenze"><?php for($i=1;$i<=$licenses['pages'];$i++): ?><a class="<?= $i===$licenses['page']?'current':'' ?>" href="?q=<?= urlencode($search) ?>&page=<?= $i ?>" <?= $i===$licenses['page']?'aria-current="page"':'' ?>><?= $i ?></a><?php endfor; ?></nav><?php endif; ?>
<dialog id="create-license"><form method="post"><div class="dialog-head"><h2>Nuova licenza</h2><button class="button secondary icon-button" type="button" data-close aria-label="Chiudi">×</button></div><div class="dialog-body"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf']) ?>"><input type="hidden" name="action" value="create"><label class="field">Nome e cognome<input class="input" name="name" maxlength="120" autocomplete="name" required></label><label class="field">Email<input class="input" type="email" name="email" autocomplete="email" required></label><label class="field">Telefono<input class="input" name="phone" maxlength="40" autocomplete="tel" required></label><label class="field">Scadenza<input class="input" type="datetime-local" name="expires_at" required></label><label class="field">Dispositivi consentiti<input class="input" type="number" name="device_limit" min="1" max="20" value="1" required></label><div class="dialog-actions"><button class="button secondary" type="button" data-close>Annulla</button><button class="button">Crea licenza</button></div></div></form></dialog>
<?php endif; ?></main><script src="assets/admin.js" defer></script></body></html>
